### ISSUE TITLE
4.4.3 checksum does not match

### ISSUE THREAD

**Issue by samliddicott** [rgl/ovftool-binaries#1]
Download form https//github.com/rgl/ovftool-binaries/raw/main/archive/VMware-ovftool-4.4.3-18663434-lin.x86_64.zip 
has md5 a586c9a830cfa5a3dddedc7d77a64156  
not 7573d4e7f2b3da87e238af14ea9340a4 
as listed in the readme.md and on the vmware download page https://developer.vmware.com/web/tool/4.4.0/ovf

Your file has certificates missing, it even has the README.txt missing

**Comment by rgl** [comment]
The links in the README point to the repository file (an HTML document), they do not point to the actual binary (you have to click the download raw file button).

Maybe they should point to the raw download instead?

**Comment by samliddicott** [comment]
I actually downloaded the zip file via the repolistory file (as you say), and took the md5 of the downloaded zip file.

I unzipped the downloaded zip file and did `diff -Nru` to compare with the official zip file, the contents are not identical.

> Maybe they should point to the raw download instead?

They definitely should because that confused me at first, but the actual zip file has the problem.

Try download it yourself.

**Comment by rgl** [comment]
Not sure what is going on your side, but here, the downloaded md5 is the same:

```console
# wget https://github.com/rgl/ovftool-binaries/raw/main/archive/VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
--2023-02-21 12:08:57--  https://github.com/rgl/ovftool-binaries/raw/main/archive/VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rgl/ovftool-binaries/main/archive/VMware-ovftool-4.4.3-18663434-lin.x86_64.zip [following]
--2023-02-21 12:08:57--  https://raw.githubusercontent.com/rgl/ovftool-binaries/main/archive/VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24001576 (23M) [application/zip]
Saving to: ‘VMware-ovftool-4.4.3-18663434-lin.x86_64.zip’

VMware-ovftool-4.4.3-18663434-lin.x86_64 100%[==================================================================================>]  22.89M  33.5MB/s    in 0.7s

2023-02-21 12:09:00 (33.5 MB/s) - ‘VMware-ovftool-4.4.3-18663434-lin.x86_64.zip’ saved [24001576/24001576]


# file VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
VMware-ovftool-4.4.3-18663434-lin.x86_64.zip: Zip archive data, at least v2.0 to extract, compression method=store

# md5sum.exe VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
7573d4e7f2b3da87e238af14ea9340a4 *VMware-ovftool-4.4.3-18663434-lin.x86_64.zip
```

**Comment by samliddicott** [comment]
I have to admit after downloading it again using wget, from the URL I mentioned (inserting the missing colon after https) that the checksum matches and the missing files are there.

I was using `aria2c -c`, (continue mode) and I suspect that combined with my previous attempts from non-raw URL, so you are correct, your repo is fine, but yes, please update the readme.md to point to the raw URL.

**Comment by rgl** [comment]
The README is now updated.
